api:
  image:
    repository: python-redis-notes-api
    tag: v1
    pullPolicy: IfNotPresent
  replicaCount: 1
  port: 8000

redis:
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  port: 6379
