apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notes-api.fullname" . }}-config
  labels:
    {{- include "notes-api.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  DEFAULT_TTL_SECONDS: {{ .Values.config.defaultTtlSeconds | quote }}
